//! Local-first completion of provider packages.
//!
//! A package leaves this module only when every enabled pin is bundled,
//! available in a local cache/backup, fetched from LuaTools or generated by
//! Hubcap. No Steam-side package installation happens here.

use crate::core::settings::load_settings;
use crate::manifest::package::{ManifestPackage, ManifestPackageFile};
use crate::manifest::pins::{pins_from_rows, DepotManifestPin, LuaManifestPins};
use crate::manifest::resolver;
use crate::providers::luatools::LuaToolsClient;
use std::collections::HashSet;

const LUATOOLS_MAX_SOURCE_ATTEMPTS: usize = 2;

pub(super) async fn download_complete_luatools_package(
    app: &tauri::AppHandle,
    app_id: u32,
    steam_path: &str,
    game_name: Option<&str>,
) -> Result<ManifestPackage, String> {
    let client = LuaToolsClient::new();
    let sources = client.available_sources(app_id).await?;
    let attempts = sources.len().min(LUATOOLS_MAX_SOURCE_ATTEMPTS);
    let mut previous_failure: Option<(String, String)> = None;

    for (index, source) in sources.iter().take(attempts).enumerate() {
        let mut package = match client.download_lua_package_from(app_id, source, game_name).await {
            Ok(package) => package,
            Err(error) => {
                return Err(match previous_failure {
                    Some((first_source, first_error)) => format!(
                        "{error} (fallback after source {first_source} could not be completed: {first_error})"
                    ),
                    None => error,
                });
            }
        };
        match complete_luatools_package(app, app_id, steam_path, &client, &mut package).await {
            Ok(()) => return Ok(package),
            Err(error) => {
                let next = sources.get(index + 1).filter(|_| index + 1 < attempts);
                match next {
                    Some(next_source) => {
                        crate::desk_log_warn!(
                            "store",
                            "LuaTools source '{}' package for {} could not be completed ({}); trying source '{}'",
                            source,
                            crate::core::logger::format_appid(app_id),
                            error,
                            next_source
                        );
                        previous_failure = Some((source.clone(), error));
                    }
                    None => {
                        return Err(match previous_failure {
                            Some((first_source, first_error)) => format!(
                                "{error} (source {first_source} was tried first: {first_error})"
                            ),
                            None => error,
                        });
                    }
                }
            }
        }
    }
    Err(format!("LuaTools has no available source for App ID {app_id}"))
}

async fn complete_luatools_package(
    app: &tauri::AppHandle,
    app_id: u32,
    steam_path: &str,
    client: &LuaToolsClient,
    package: &mut ManifestPackage,
) -> Result<(), String> {
    let bundled = bundled_manifest_names(&package.manifest_files);
    let pins: Vec<DepotManifestPin> = enabled_pins_from_content(&package.lua_content)
        .into_iter()
        .filter(|pin| !bundled.contains(&resolver::manifest_file_name(pin)))
        .collect();
    if pins.is_empty() {
        crate::desk_log_info!(
            "store",
            "LuaTools package for {} is self-contained: {} manifest(s) bundled, nothing to complete",
            crate::core::logger::format_appid(app_id),
            package.manifest_files.len()
        );
        return Ok(());
    }

    let completeness = resolver::verify_available(steam_path, app_id, &pins);
    if completeness.missing.is_empty() {
        crate::desk_log_info!(
            "store",
            "LuaTools package for {}: {} pin(s) not bundled but already available locally",
            crate::core::logger::format_appid(app_id),
            completeness.verified
        );
        return Ok(());
    }
    crate::desk_log_info!(
        "store",
        "LuaTools package for {} needs {} manifest(s) (bundled={}, local={}): completing through LuaTools",
        crate::core::logger::format_appid(app_id),
        completeness.missing.len(),
        package.manifest_files.len(),
        completeness.verified
    );

    let completion = client.complete_manifests(app_id, &completeness.missing).await;
    let fetched_count = completion.fetched.len();
    package.manifest_files.extend(completion.fetched);
    if completion.failed.is_empty() {
        crate::desk_log_info!(
            "store",
            "LuaTools completion for {}: {} manifest(s) fetched, package complete",
            crate::core::logger::format_appid(app_id),
            fetched_count
        );
        return Ok(());
    }

    let still_missing: Vec<DepotManifestPin> = completion
        .failed
        .iter()
        .map(|(pin, _)| pin.clone())
        .collect();
    let hubcap_key = load_settings(app).hubcap_api_key.trim().to_string();
    let mut unresolved = still_missing.clone();
    if !hubcap_key.is_empty() && hubcap_key != "oureveryday_public" {
        crate::desk_log_info!(
            "store",
            "LuaTools completion for {}: {} manifest(s) not served by LuaTools, trying Hubcap generation",
            crate::core::logger::format_appid(app_id),
            still_missing.len()
        );
        match resolver::resolve(resolver::ManifestRequest {
            steam_path: steam_path.to_string(),
            app_id,
            pins: still_missing,
            generation: resolver::Generation::SettingsKey(hubcap_key.clone()),
        })
        .await
        {
            Ok(resolution) => {
                package.manifest_files.extend(resolution.generated);
                unresolved = resolution.missing;
            }
            Err(error) => crate::desk_log_warn!(
                "store",
                "Hubcap fallback for LuaTools package {} failed: {}",
                crate::core::logger::format_appid(app_id),
                error
            ),
        }
    }

    if unresolved.is_empty() {
        crate::desk_log_info!(
            "store",
            "LuaTools completion for {}: {} fetched from LuaTools, rest generated through Hubcap, package complete",
            crate::core::logger::format_appid(app_id),
            fetched_count
        );
        return Ok(());
    }

    let reasons: Vec<String> = completion
        .failed
        .iter()
        .filter(|(pin, _)| unresolved.contains(pin))
        .map(|(pin, reason)| format!("{}_{} ({})", pin.depot_id, pin.manifest_id, reason))
        .collect();
    crate::desk_log_error!(
        "store",
        "LuaTools completion for {} incomplete: {} manifest(s) unavailable: {}",
        crate::core::logger::format_appid(app_id),
        unresolved.len(),
        reasons.join("; ")
    );
    let hint = if hubcap_key.is_empty() {
        " Configure a Hubcap API key in Settings to generate the missing manifests, or retry later."
    } else {
        " Retry later or try another source."
    };
    Err(format!(
        "LuaTools could not provide {} of the {} manifest(s) this Lua references: {}.{}",
        unresolved.len(),
        pins.len(),
        reasons.join("; "),
        hint
    ))
}

pub(super) async fn complete_hubcap_package(
    app_id: u32,
    steam_path: &str,
    package: &mut ManifestPackage,
    api_key: &str,
) -> Result<(), String> {
    let bundled = bundled_manifest_names(&package.manifest_files);
    let pins: Vec<DepotManifestPin> = enabled_pins_from_content(&package.lua_content)
        .into_iter()
        .filter(|pin| !bundled.contains(&resolver::manifest_file_name(pin)))
        .collect();
    let generation = if api_key.trim().is_empty() || api_key == "oureveryday_public" {
        resolver::Generation::LocalOnly
    } else {
        resolver::Generation::PreValidatedKey(api_key.to_string())
    };
    let resolution = resolver::resolve(resolver::ManifestRequest {
        steam_path: steam_path.to_string(),
        app_id,
        pins,
        generation,
    })
    .await?;
    if !resolution.is_complete() {
        return Err("This package needs manifest files that are not stored locally. Configure a valid Hubcap API key; the obsolete request-code path is not used.".to_string());
    }
    package.manifest_files.extend(resolution.generated);
    Ok(())
}

pub(super) async fn complete_specific_package(
    app_id: u32,
    steam_path: &str,
    package: &mut ManifestPackage,
    api_key: &str,
) -> Result<(), String> {
    let bundled = bundled_manifest_names(&package.manifest_files);
    let pins: Vec<DepotManifestPin> = enabled_pins_from_content(&package.lua_content)
        .into_iter()
        .filter(|pin| !bundled.contains(&resolver::manifest_file_name(pin)))
        .collect();
    let generation = if api_key == "oureveryday_public" {
        resolver::Generation::LocalOnly
    } else {
        resolver::Generation::PreValidatedKey(api_key.to_string())
    };
    let resolution = resolver::resolve(resolver::ManifestRequest {
        steam_path: steam_path.to_string(),
        app_id,
        pins,
        generation,
    })
    .await?;
    if !resolution.is_complete() {
        return Err("This specific version includes manifests not present locally. Configure a valid Hubcap API key; the obsolete request-code path is not used.".to_string());
    }
    package.manifest_files.extend(resolution.generated);
    Ok(())
}

pub(super) fn enabled_pins_from_content(lua_content: &str) -> Vec<DepotManifestPin> {
    pins_from_rows(
        LuaManifestPins::rows_from_content(lua_content)
            .into_iter()
            .filter(|row| row.enabled),
    )
}

fn bundled_manifest_names(package_files: &[ManifestPackageFile]) -> HashSet<String> {
    package_files
        .iter()
        .filter_map(|manifest| {
            let name = std::path::Path::new(&manifest.file_name)
                .file_name()
                .and_then(|value| value.to_str())?;
            (!manifest.bytes.is_empty()).then_some(name.to_string())
        })
        .collect()
}
