#include "pch.h"
#include "hooks/wire/UserStatsSnapshot.h"

#include <algorithm>
#include <cstdio>
#include <ctime>
#include <fstream>

#include "core/Logger.h"
#include "hooks/wire/BackupIo.h"

namespace ac::backup::snapshot {
namespace {

constexpr const char* kModule = "Wire.Achievement";

}  // namespace

std::string SnapshotPath(steam::AppId appId, std::uint32_t accountId) {
    const std::string dir = io::BackupDirForApp(appId);
    if (dir.empty()) return {};
    return dir + "\\UserGameStats_" + std::to_string(accountId) + "_" +
           std::to_string(appId) + ".json";
}

SnapshotData Load(const std::string& path) {
    SnapshotData out;
    std::ifstream ifs(path);
    if (!ifs.is_open()) return out;
    std::string line;
    while (std::getline(ifs, line)) {
        if (const std::size_t p = line.find("{\"id\":"); p != std::string::npos) {
            UnlockEntry e{};
            if (std::sscanf(line.c_str() + p, "{\"id\": %u, \"unlock_time\": %u",
                            &e.id, &e.unlockTime) == 2) {
                out.unlocks.push_back(e);
            }
            continue;
        }
        if (const std::size_t p = line.find("{\"sid\":"); p != std::string::npos) {
            StatEntry st{};
            if (std::sscanf(line.c_str() + p, "{\"sid\": %u, \"value\": %u",
                            &st.id, &st.value) == 2) {
                out.stats.push_back(st);
            }
        }
    }
    return out;
}

void Save(const std::string& path, steam::AppId appId, std::uint32_t accountId,
          std::uint64_t steamId64, const SnapshotData& snap) {
    if (path.empty()) return;
    const std::string tmp = path + ".tmp";
    {
        std::ofstream out(tmp, std::ios::trunc);
        if (!out.is_open()) {
            AC_LOG_WARN(kModule, "Backup: cannot write %s.", tmp.c_str());
            return;
        }
        out << "{\n";
        out << "  \"_format\": \"aether-achievement-mirror-v1\",\n";
        out << "  \"_note\": \"snapshot generated by AetherDLL; rebuild the .bin with Tools/achievement_decoder.py rebuild\",\n";
        out << "  \"appid\": " << appId << ",\n";
        out << "  \"account_id\": " << accountId << ",\n";
        out << "  \"steamid64\": " << steamId64 << ",\n";
        out << "  \"updated\": \"" << io::FormatWallClockNow() << "\",\n";
        out << "  \"updated_unix\": " << static_cast<long long>(std::time(nullptr)) << ",\n";
        out << "  \"achievements\": [\n";
        for (std::size_t i = 0; i < snap.unlocks.size(); ++i) {
            // unlock_time 0 = baseline (data reale sconosciuta): mostrata come
            // "unknown"; il rebuild del .bin usa updated_unix come fallback.
            const UnlockEntry& e = snap.unlocks[i];
            out << "    {\"id\": " << e.id
                << ", \"unlock_time\": " << e.unlockTime
                << ", \"unlocked_at\": \""
                << (e.unlockTime != 0 ? io::FormatUnixTime(e.unlockTime) : std::string("unknown"))
                << "\""
                << ", \"bucket\": " << (e.id / 32u)
                << ", \"bit\": " << (e.id % 32u) << "}"
                << (i + 1 < snap.unlocks.size() ? "," : "") << "\n";
        }
        out << "  ],\n";
        out << "  \"stats\": [\n";
        for (std::size_t i = 0; i < snap.stats.size(); ++i) {
            out << "    {\"sid\": " << snap.stats[i].id
                << ", \"value\": " << snap.stats[i].value << "}"
                << (i + 1 < snap.stats.size() ? "," : "") << "\n";
        }
        out << "  ]\n";
        out << "}\n";
        out.flush();
    }
    if (!io::AtomicReplace(tmp, path)) {
        AC_LOG_WARN(kModule, "Backup: cannot replace %s (the .tmp file remains on disk).",
                    path.c_str());
    }
}

void MergeUnlock(SnapshotData& snap, std::uint32_t achievementId, std::uint32_t unlockTime) {
    for (auto& e : snap.unlocks) {
        if (e.id != achievementId) continue;
        // Regola: vince il tempo PIÙ ANTICO, ma 0 (baseline sconosciuta) viene
        // sostituito da qualsiasi tempo reale.
        if (e.unlockTime == 0) e.unlockTime = unlockTime;
        else if (unlockTime != 0 && unlockTime < e.unlockTime) e.unlockTime = unlockTime;
        return;
    }
    snap.unlocks.push_back(UnlockEntry{achievementId, unlockTime});
}

void MergeStat(SnapshotData& snap, std::uint32_t statId, std::uint32_t value) {
    for (auto& st : snap.stats) {
        if (st.id == statId) {
            st.value = value;   // ultimo valore committato vince
            return;
        }
    }
    snap.stats.push_back(StatEntry{statId, value});
}

bool HasUnlock(const SnapshotData& snap, std::uint32_t achievementId) {
    return std::any_of(snap.unlocks.begin(), snap.unlocks.end(),
                       [achievementId](const UnlockEntry& e) { return e.id == achievementId; });
}

bool HasStat(const SnapshotData& snap, std::uint32_t statId) {
    return std::any_of(snap.stats.begin(), snap.stats.end(),
                       [statId](const StatEntry& st) { return st.id == statId; });
}

void SortAll(SnapshotData& snap) {
    std::sort(snap.unlocks.begin(), snap.unlocks.end(),
              [](const UnlockEntry& a, const UnlockEntry& b) { return a.id < b.id; });
    std::sort(snap.stats.begin(), snap.stats.end(),
              [](const StatEntry& a, const StatEntry& b) { return a.id < b.id; });
}

}  // namespace ac::backup::snapshot
