file(REMOVE_RECURSE "${TEST_BINARY_DIR}")
file(MAKE_DIRECTORY "${TEST_BINARY_DIR}/source")
file(WRITE "${TEST_BINARY_DIR}/source/listed.cpp" "int listed() { return 0; }\n")
file(WRITE "${TEST_BINARY_DIR}/source/CMakeLists.txt"
"cmake_minimum_required(VERSION 3.20)\nproject(Inventory LANGUAGES CXX)\ninclude(\"${CHECK_MODULE}\")\nadd_library(sample listed.cpp)\naether_check_sources(sample)\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${TEST_BINARY_DIR}/source" -B "${TEST_BINARY_DIR}/pass" RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Valid inventory rejected: ${error}")
endif()
file(WRITE "${TEST_BINARY_DIR}/source/orphan.cpp" "int orphan() { return 0; }\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${TEST_BINARY_DIR}/source" -B "${TEST_BINARY_DIR}/fail" RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE error)
if(result EQUAL 0 OR NOT error MATCHES "Uncompiled source")
    message(FATAL_ERROR "Orphan was not correctly rejected: ${error}")
endif()
