//! Single local-first manifest resolver shared by every pipeline that needs
//! pinned `.manifest` files on disk (store downloads, version switching,
//! manual per-depot edits, and the explicit per-game repair).
//!
//! The resolution order is fixed and is the SAME definition of "present" used
//! by planning and by the completeness gate, so the two can never disagree
//! (the original B1 bug):
//!
//!   1. `<Steam>\depotcache`               (primary — where Steam reads)
//!   2. `<Steam>\config\depotcache`        (Steam's secondary cache)
//!   3. `<AetherData>\backup\<appid>\lua`  (Aether's per-game backup)
//!
//! Hits from (2)/(3) are published into (1) with byte verification before
//! anything else happens; only pins absent from all three locations are
//! offered to the authenticated provider. Generated bytes are returned to the
//! caller — each pipeline commits them inside its own install transaction
//! (Lua+manifests atomically, pre-Lua staging, or a direct install).
//!
//! Every writer into `depotcache` (package installs, generated-manifest
//! installs, local restores) shares one commit gate, so concurrent pipelines
//! can never collide on the temp/final file names.

use std::path::PathBuf;
use std::sync::{Mutex, OnceLock};
use std::time::Instant;

use crate::manifest::package::ManifestPackageFile;
use crate::manifest::pins::DepotManifestPin;
use crate::providers::hubcap::HubcapClient;

/// Serializes every commit into Steam's `depotcache`. Package installs
/// (`SteamCompat`), generated-manifest installs, and local-first restores all
/// stage temp files in that folder and rename onto the same final names; one
/// process-wide gate keeps concurrent pipelines from colliding.
pub(crate) fn depotcache_commit_gate() -> &'static Mutex<()> {
    static GATE: OnceLock<Mutex<()>> = OnceLock::new();
    GATE.get_or_init(|| Mutex::new(()))
}

/// File name Steam (and the AetherData backup layout) uses for one exact
/// manifest — the pin's identity on disk.
pub fn manifest_file_name(pin: &DepotManifestPin) -> String {
    format!("{}_{}.manifest", pin.depot_id, pin.manifest_id)
}

/// `"depot:manifest"` labels for logs and user-facing error messages.
pub fn missing_labels(pins: &[DepotManifestPin]) -> Vec<String> {
    pins.iter()
        .map(|pin| format!("{}:{}", pin.depot_id, pin.manifest_id))
        .collect()
}

/// Finds the exact local manifest in Steam's two cache folders or in the
/// per-game AetherData backup. Empty files are not considered local hits.
fn exact_local_manifest_path(
    steam_path: &str,
    app_id: u32,
    pin: &DepotManifestPin,
) -> Option<PathBuf> {
    let file_name = manifest_file_name(pin);
    let mut search_dirs = vec![PathBuf::from(steam_path).join("depotcache")];
    search_dirs.push(PathBuf::from(steam_path).join("config").join("depotcache"));
    search_dirs.push(
        crate::core::paths::LocalAppPaths::data_root()
            .join("backup")
            .join(app_id.to_string())
            .join("lua"),
    );
    search_dirs
        .into_iter()
        .map(|dir| dir.join(&file_name))
        .find(|path| {
            path.is_file()
                && std::fs::metadata(path)
                    .map(|meta| meta.len() > 0)
                    .unwrap_or(false)
        })
}

/// Outcome of the local (network-free) restore pass.
#[derive(Debug, Clone, Default)]
pub(crate) struct LocalRestoreOutcome {
    /// Pins already valid in the primary depotcache (no write needed).
    pub already_local: usize,
    /// Pins copied into depotcache from the backup or the secondary cache.
    pub restored: usize,
    /// Pins that are not available anywhere on disk.
    pub missing: Vec<DepotManifestPin>,
}

/// Publishes every locally available manifest (per-game AetherData backup or
/// Steam's secondary `config\depotcache`) into the primary `depotcache` and
/// reports the pins that are still missing afterwards. Idempotent: files
/// already valid in `depotcache` are never rewritten, so calling it again —
/// for planning and before a completeness gate — is a cheap no-op.
///
/// This is a blocking function: callers on the async runtime must go through
/// [`resolve`] (which runs it on the blocking pool).
pub(crate) fn restore_local_blocking(
    steam_path: &str,
    app_id: u32,
    pins: &[DepotManifestPin],
) -> Result<LocalRestoreOutcome, String> {
    crate::desk_log_debug!(
        "manifest",
        "Local manifest restore start app_id={} pins={} steam_path_configured={}",
        app_id,
        pins.len(),
        !steam_path.trim().is_empty()
    );
    let depotcache = PathBuf::from(steam_path).join("depotcache");
    std::fs::create_dir_all(&depotcache)
        .map_err(|e| format!("Could not create Steam depotcache: {e}"))?;

    let mut outcome = LocalRestoreOutcome::default();
    let _commit_guard = depotcache_commit_gate()
        .lock()
        .map_err(|_| "Manifest installation scheduler is unavailable".to_string())?;

    for pin in pins {
        let file_name = manifest_file_name(pin);
        let Some(source) = exact_local_manifest_path(steam_path, app_id, pin) else {
            crate::desk_log_debug!(
                "manifest",
                "Local manifest missing app_id={} depot_id={} manifest_id={}",
                app_id,
                pin.depot_id,
                pin.manifest_id
            );
            outcome.missing.push(pin.clone());
            continue;
        };
        let destination = depotcache.join(&file_name);
        let destination_valid = destination.is_file()
            && std::fs::metadata(&destination)
                .map(|metadata| metadata.len() > 0)
                .unwrap_or(false);
        if destination_valid {
            // A valid copy already sits where Steam reads: nothing to do. (If
            // the source were the depotcache file itself, it would be valid by
            // definition — `exact_local_manifest_path` skips empty files.)
            outcome.already_local += 1;
            continue;
        }
        let temporary = destination.with_extension("manifest.tmp");
        let _ = std::fs::remove_file(&destination);
        std::fs::copy(&source, &temporary)
            .map_err(|e| format!("Could not restore local manifest {file_name}: {e}"))?;
        std::fs::rename(&temporary, &destination)
            .map_err(|e| format!("Could not install local manifest {file_name}: {e}"))?;
        let source_len = std::fs::metadata(&source)
            .map_err(|e| format!("Could not verify source manifest {file_name}: {e}"))?
            .len();
        let destination_len = std::fs::metadata(&destination)
            .map_err(|e| format!("Could not verify restored manifest {file_name}: {e}"))?
            .len();
        if source_len == 0 || destination_len != source_len {
            return Err(format!(
                "Restored local manifest {file_name} failed verification (source {source_len} bytes, destination {destination_len} bytes)"
            ));
        }
        crate::desk_log_debug!(
            "manifest",
            "Restored local manifest app_id={} file={} bytes={}",
            app_id,
            file_name,
            destination_len
        );
        outcome.restored += 1;
    }
    crate::desk_log_info!(
        "manifest",
        "Local manifest restore complete app_id={} already_local={} restored={} missing={}",
        app_id,
        outcome.already_local,
        outcome.restored,
        outcome.missing.len()
    );
    Ok(outcome)
}

/// How pins that are not available on disk may be satisfied through Hubcap.
#[derive(Debug, Clone)]
pub enum Generation {
    /// Disk-only resolution: unrestorable pins are reported in
    /// [`ManifestResolution::missing`] instead of being generated, and the
    /// caller turns them into its own "configure a key" guidance. No provider
    /// traffic at all.
    LocalOnly,
    /// Validate the key — but only when generation is actually required —
    /// then generate. Used by flows that read the key straight from settings.
    SettingsKey(String),
    /// Generate without re-validating: the caller's command already validated
    /// this key earlier in its transaction (e.g. the store's cached
    /// validation). Avoids duplicate validation round-trips.
    PreValidatedKey(String),
}

/// One local-first manifest resolution request.
#[derive(Debug, Clone)]
pub struct ManifestRequest {
    pub steam_path: String,
    pub app_id: u32,
    /// The pins that must be available when the call returns. Callers decide
    /// which Lua rows these are (enabled rows, addappid-active rows, …);
    /// the resolver is agnostic.
    pub pins: Vec<DepotManifestPin>,
    pub generation: Generation,
}

/// What [`resolve`] hands back to the caller: the only two things a pipeline
/// needs to continue — the bytes it still has to commit and the pins it could
/// not satisfy anywhere. The local-restore tallies (`already_local`,
/// `restored`) are diagnostics, not decisions: they stay inside
/// [`restore_local_blocking`], which already logs them, so no caller can read
/// (and none can mistakenly branch on) a stale copy.
#[derive(Debug, Clone, Default)]
pub struct ManifestResolution {
    /// Provider-generated manifest files, ready for the caller's commit
    /// (Lua transaction, pre-Lua staging, or direct install — the resolver
    /// never writes generated bytes itself).
    pub generated: Vec<ManifestPackageFile>,
    /// Pins that are still unavailable anywhere. Empty means every requested
    /// pin is satisfied.
    pub missing: Vec<DepotManifestPin>,
}

impl ManifestResolution {
    pub fn is_complete(&self) -> bool {
        self.missing.is_empty()
    }
}

/// The one entry point every pipeline uses to answer "give me these
/// manifests": local restore first (backup and secondary-cache hits are
/// published into depotcache with byte verification), then — only for the
/// pins still absent — authenticated provider generation. See the module docs
/// for the fixed lookup order.
pub async fn resolve(request: ManifestRequest) -> Result<ManifestResolution, String> {
    let ManifestRequest {
        steam_path,
        app_id,
        pins,
        generation,
    } = request;

    // The restore pass touches the filesystem for every pin: keep it off the
    // async runtime.
    let outcome = tauri::async_runtime::spawn_blocking(move || {
        restore_local_blocking(&steam_path, app_id, &pins)
    })
    .await
    .map_err(|error| format!("Local manifest preparation failed: {error}"))??;

    let mut resolution = ManifestResolution {
        generated: Vec::new(),
        missing: outcome.missing,
    };
    if resolution.is_complete() {
        return Ok(resolution);
    }

    match generation {
        Generation::LocalOnly => Ok(resolution),
        Generation::SettingsKey(api_key) => {
            let client = HubcapClient::new(api_key);
            if !client.validate_api_key().await? {
                return Err(
                    "Hubcap API key is not valid or is not allowed to make requests.".to_string(),
                );
            }
            resolution.generated =
                generate_missing_manifests(client, std::mem::take(&mut resolution.missing))
                    .await?;
            Ok(resolution)
        }
        Generation::PreValidatedKey(api_key) => {
            let client = HubcapClient::new(api_key);
            resolution.generated =
                generate_missing_manifests(client, std::mem::take(&mut resolution.missing))
                    .await?;
            Ok(resolution)
        }
    }
}

/// Generates missing pins through Hubcap. Strictly serial by design: the
/// provider rate-limits generation independently of the daily quota, and the
/// process-wide scheduler already deduplicates and enforces cadence across
/// game, Workshop, and store flows — a second concurrent request would only
/// add avoidable 429 pressure.
async fn generate_missing_manifests(
    client: HubcapClient,
    missing: Vec<DepotManifestPin>,
) -> Result<Vec<ManifestPackageFile>, String> {
    let started = Instant::now();
    crate::desk_log_info!(
        "manifest",
        "Manifest generation batch start missing={}",
        missing.len()
    );
    let mut files = Vec::new();
    for pin in missing {
        let (pin, result) = generate_one(client.clone(), pin).await;
        let bytes = result.map_err(|error| {
            format!(
                "Hubcap could not generate manifest {}_{}: {}",
                pin.depot_id, pin.manifest_id, error
            )
        })?;
        files.push(ManifestPackageFile {
            file_name: manifest_file_name(&pin),
            bytes,
        });
    }
    crate::desk_log_info!(
        "manifest",
        "Manifest generation batch complete generated={} elapsed_ms={}",
        files.len(),
        started.elapsed().as_millis()
    );
    Ok(files)
}

/// One serialized generation request with structured start/complete logging.
async fn generate_one(
    client: HubcapClient,
    pin: DepotManifestPin,
) -> (DepotManifestPin, Result<Vec<u8>, String>) {
    crate::desk_log_info!(
        "manifest",
        "Manifest generation start depot_id={} manifest_id={}",
        pin.depot_id,
        pin.manifest_id
    );
    let result = match pin.manifest_id.parse::<u64>() {
        Ok(gid) => client.generate_manifest(pin.depot_id, gid).await,
        Err(_) => Err(format!("Invalid manifest GID for depot {}", pin.depot_id)),
    };
    crate::desk_log_info!(
        "manifest",
        "Manifest generation complete depot_id={} manifest_id={} success={}",
        pin.depot_id,
        pin.manifest_id,
        result.is_ok()
    );
    (pin, result)
}

/// Result of the shared completeness gate.
#[derive(Debug, Clone, Default)]
pub struct CompletenessReport {
    /// Pins available (non-empty file) in at least one of the three
    /// resolution locations.
    pub verified: usize,
    /// Pins unavailable everywhere. Empty means the gate passes.
    pub missing: Vec<DepotManifestPin>,
}

/// Completeness gate shared by every pipeline: each pin must be available in
/// the primary depotcache, Steam's secondary cache, or the per-game backup —
/// exactly the locations [`resolve`] restores from, so a manifest that counts
/// as resolved can never fail this gate.
///
/// Read-only (a handful of `stat` calls): safe to call from async contexts
/// and from inside blocking pipeline phases alike.
pub fn verify_available(
    steam_path: &str,
    app_id: u32,
    pins: &[DepotManifestPin],
) -> CompletenessReport {
    let mut report = CompletenessReport::default();
    for pin in pins {
        if exact_local_manifest_path(steam_path, app_id, pin).is_some() {
            report.verified += 1;
        } else {
            report.missing.push(pin.clone());
        }
    }
    report
}
