import { useCallback, useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
import type { LuaToolsAuthStatus } from './types';

const SIGNED_OUT: LuaToolsAuthStatus = { signedIn: false, displayName: null, email: null };

type StatusKind = 'info' | 'success' | 'error';

export function useLuaToolsAuth(showStatus: (text: string, kind: StatusKind) => void) {
  const [auth, setAuth] = useState<LuaToolsAuthStatus>(SIGNED_OUT);
  const [busy, setBusy] = useState(false);
  const [oauthBusy, setOauthBusy] = useState(false);
  const [modalOpen, setModalOpen] = useState(false);
  const [mode, setMode] = useState<'choice' | 'code'>('choice');
  const [code, setCode] = useState('');
  const [error, setError] = useState('');

  const refresh = useCallback(async () => {
    try { setAuth(await invoke<LuaToolsAuthStatus>('get_luatools_auth_status')); }
    catch (err) { console.warn('[settings] failed to load LuaTools auth status:', err); }
  }, []);

  const open = useCallback(() => {
    setMode('choice'); setCode(''); setError(''); setModalOpen(true);
  }, []);
  const close = useCallback(() => {
    if (busy) return;
    setModalOpen(false); setMode('choice'); setCode(''); setError('');
  }, [busy]);

  const signIn = useCallback(async () => {
    if (busy) return;
    setModalOpen(false); setBusy(true); setOauthBusy(true);
    showStatus('Complete the LuaTools OAuth sign-in in Discord or your browser...', 'info');
    try {
      const next = await invoke<LuaToolsAuthStatus>('sign_in_luatools');
      setAuth(next);
      showStatus(`LuaTools connected${next.displayName ? ` as ${next.displayName}` : ''}.`, 'success');
    } catch (err) {
      if (!String(err).toLowerCase().includes('cancelled')) showStatus(`LuaTools sign-in failed: ${err}`, 'error');
    } finally { setOauthBusy(false); setBusy(false); }
  }, [busy, showStatus]);

  const cancelOAuth = useCallback(async () => {
    try { await invoke('cancel_luatools_sign_in'); showStatus('LuaTools sign-in cancelled.', 'info'); }
    catch (err) { showStatus(`Could not cancel LuaTools sign-in: ${err}`, 'error'); }
    finally { setOauthBusy(false); setBusy(false); }
  }, [showStatus]);

  const codeSignIn = useCallback(async () => {
    if (busy) return;
    const normalized = code.trim().toUpperCase();
    if (normalized.length !== 6) { setError('Enter the 6-character code generated by @Luie.'); return; }
    setBusy(true); setError('');
    try {
      const next = await invoke<LuaToolsAuthStatus>('sign_in_luatools_with_code', { code: normalized });
      setAuth(next); setModalOpen(false); setMode('choice'); setCode('');
      showStatus(`LuaTools connected privately${next.displayName ? ` as ${next.displayName}` : ''}.`, 'success');
    } catch (err) { setError(String(err)); }
    finally { setBusy(false); }
  }, [busy, code, showStatus]);

  const signOut = useCallback(async () => {
    if (busy) return;
    setBusy(true);
    try { await invoke('sign_out_luatools'); setAuth(SIGNED_OUT); showStatus('LuaTools disconnected.', 'success'); }
    catch (err) { showStatus(`LuaTools sign-out failed: ${err}`, 'error'); }
    finally { setBusy(false); }
  }, [busy, showStatus]);

  const changeMode = useCallback((next: 'choice' | 'code') => { setMode(next); setError(''); }, []);
  const changeCode = useCallback((value: string) => { setCode(value.replace(/[^a-z0-9]/gi, '').toUpperCase()); setError(''); }, []);

  return { auth, busy, oauthBusy, modalOpen, mode, code, error, refresh, open, close, signIn, cancelOAuth, codeSignIn, signOut, changeMode, changeCode };
}
