use std::path::PathBuf;

use crate::manifest::package::ManifestPackageFile;
use crate::manifest::pins::{DepotManifestPin, LuaManifestPins};
use crate::steam::acf::SteamAcfEditor;
use crate::steam::compat::SteamCompat;
use crate::versioning::error::VersionError;
use crate::versioning::model::ApplyVersionReport;

/// Progress callback used by the pipeline: `(percent, human message)`.
pub type ProgressFn<'a> = dyn Fn(u8, &str) + Send + Sync + 'a;

/// Applies the safely resolved portion of a build snapshot. Every step is
/// idempotent and the report always describes the real state that was reached:
///
///  1. validate the game has a stplug-in Lua
///  2. preserve the pre-change Lua into the AetherData backup tree
///     (`backup/<appid>/lua/history/`, deduplicated by content — no more
///     `.lua.bak` files in stplug-in)
///  3. pin every manifest resolved at or before the target into the Lua;
///     depots outside the available history remain byte-for-byte unchanged —
///     LumaCore picks the resolved changes up live
///  4. count which pinned `.manifest` files already exist locally
///  5. verify the Lua pin count did not change and report
pub fn apply_build_version(
    app_id: u32,
    build_id: u64,
    steam_path: &str,
    library_path: &str,
    pins: &[DepotManifestPin],
    generated_manifests: &[ManifestPackageFile],
    progress: &ProgressFn<'_>,
) -> Result<ApplyVersionReport, VersionError> {
    let lua = LuaManifestPins::new(steam_path.to_string(), app_id);
    if !lua.path_exists() {
        return Err(VersionError::LuaMissing(
            lua.lua_path().display().to_string(),
        ));
    }
    let before_rows = lua.rows_from_file().map_err(VersionError::Lua)?;
    let before_count = before_rows.len();
    crate::desk_log_info!(
        "versioning",
        "Apply pipeline for app {} (build {}): {} Lua depot row(s), {} pin(s) to write",
        app_id,
        build_id,
        before_count,
        pins.len()
    );

    progress(10, "Backing up the game Lua");
    // Niente più .lua.bak in stplug-in: il contenuto PRE-modifica viene
    // preservato nell'albero di backup AetherData (history/ se non già noto).
    let history_dir = crate::core::backup::GameBackup::for_app(app_id)
        .map(|backup| {
            let dir = backup.lua_dir().join(crate::core::backup::LUA_HISTORY_SUBDIR);
            if let Ok(pre_lua) = std::fs::read(lua.lua_path()) {
                if let Err(e) = backup.store_history_version(app_id, &pre_lua) {
                    crate::desk_log_warn!(
                        "versioning",
                        "Could not archive pre-change Lua for app {}: {}",
                        app_id,
                        e
                    );
                }
            }
            dir
        })
        .unwrap_or_else(|e| {
            crate::desk_log_warn!(
                "versioning",
                "Backup tree unavailable for app {}: {}",
                app_id,
                e
            );
            std::path::PathBuf::from("unavailable")
        });

    // Generated bytes are fetched before this blocking phase. Install them
    // atomically before Steam can observe the new Lua, so a successful version
    // switch never points at a manifest that has not been staged yet.
    if !generated_manifests.is_empty() {
        let installed = SteamCompat::new(steam_path.to_string())
            .install_manifest_files(generated_manifests)
            .map_err(VersionError::Lua)?;
        crate::desk_log_info!(
            "versioning",
            "Generated manifest install completed app_id={} installed={} requested={}",
            app_id,
            installed,
            generated_manifests.len()
        );
    }

    let staged = crate::manifest::resolver::verify_available(steam_path, app_id, pins);
    crate::desk_log_info!(
        "versioning",
        "Pre-apply manifest gate app_id={} found={} missing={}",
        app_id,
        staged.verified,
        staged.missing.len()
    );
    if !staged.missing.is_empty() {
        return Err(VersionError::Lua(format!(
            "Cannot apply build {build_id}: {} manifest(s) are still missing or empty after staging: {}",
            staged.missing.len(),
            crate::manifest::resolver::missing_labels(&staged.missing).join(", ")
        )));
    }

    progress(30, "Pinning build manifests in the Lua");
    let apply_result = match lua.apply_build_pins(pins) {
        Ok(result) => {
            crate::desk_log_info!(
                "versioning",
                "Lua pins written for app {}: {} applied from the reconstructed build snapshot",
                app_id,
                result.applied_pins
            );
            result
        }
        Err(e) => {
            crate::desk_log_error!(
                "versioning",
                "Lua pin write failed for app {}: {}",
                app_id,
                e
            );
            return Err(VersionError::Lua(e));
        }
    };

    // La versione con i pin applicati è una VERSIONE MODIFICATA: va in
    // history/ (l'originale pristino nel backup non si tocca). Aggiornamento
    // immediato, non più al riavvio di Desk. Best-effort.
    if let Ok(final_lua) = std::fs::read_to_string(lua.lua_path()) {
        match crate::core::backup::GameBackup::for_app(app_id)
            .and_then(|backup| backup.store_history_version(app_id, final_lua.as_bytes()))
        {
            Ok(true) => crate::desk_log_info!(
                "versioning",
                "Lua version archived to history for app {} right after pin apply",
                app_id
            ),
            Ok(false) => crate::desk_log_info!(
                "versioning",
                "Lua version for app {} already known (history unchanged)",
                app_id
            ),
            Err(e) => crate::desk_log_warn!(
                "versioning",
                "History archive failed for app {} (will retry at next Desk start): {}",
                app_id,
                e
            ),
        }
    }

    // Keep the final Lua and every exact manifest it references in the same
    // backup tree. This also captures generated files, not only provider ZIPs.
    if let Ok(final_lua) = std::fs::read_to_string(lua.lua_path()) {
        if let Ok(backup) = crate::core::backup::GameBackup::for_app(app_id) {
            let depotcache = PathBuf::from(steam_path).join("depotcache");
            let backup_report = backup.backup_referenced_manifests(&final_lua, &depotcache);
            if backup_report.errors > 0 || backup_report.missing > 0 {
                crate::desk_log_debug!(
                    "versioning",
                    "Final manifest backup for app {}: {} copied, {} unchanged, {} missing, {} errors",
                    app_id,
                    backup_report.copied,
                    backup_report.unchanged,
                    backup_report.missing,
                    backup_report.errors
                );
            }
        }
    }

    progress(55, "Checking local manifest files");
    let completeness = crate::manifest::resolver::verify_available(steam_path, app_id, pins);
    let manifests_found = completeness.verified;
    let manifests_missing = crate::manifest::resolver::missing_labels(&completeness.missing);
    crate::desk_log_info!(
        "versioning",
        "Local manifests for app {}: {} of {} already in depotcache",
        app_id,
        manifests_found,
        pins.len()
    );
    if !manifests_missing.is_empty() {
        crate::desk_log_error!(
            "versioning",
            "Manifest completion gate failed app_id={} missing={}",
            app_id,
            manifests_missing.len()
        );
        return Err(VersionError::Lua(format!(
            "Build {build_id} was not completed: {} referenced manifest(s) are missing or empty after install",
            manifests_missing.len()
        )));
    }

    progress(75, "Syncing the Steam ACF");
    // Best-effort: se l'ACF manca o è bloccato si logga un WARN e si prosegue
    // (la coda "pending ACF" è stata rimossa: i pin nel .lua fanno il lavoro
    // vero, l'ACF è solo metadato).
    let acf = SteamAcfEditor::for_app(library_path, app_id);
    let acf_synced_now = match acf.apply_build(build_id, pins) {
        Ok(()) => true,
        Err(acf_error) => {
            crate::desk_log_warn!(
                "versioning",
                "ACF sync for app {} (build {}) skipped: {}",
                app_id,
                build_id,
                acf_error
            );
            false
        }
    };

    progress(95, "Verifying");
    let after_count = lua.rows_from_file().map_err(VersionError::Lua)?.len();
    if after_count != before_count {
        crate::desk_log_error!(
            "versioning",
            "Verification failed for app {}: pin count {} -> {}",
            app_id,
            before_count,
            after_count
        );
        return Err(VersionError::Lua(format!(
            "Verification failed: setManifestid count changed from {} to {} after applying the build. Restore from {} to undo.",
            before_count,
            after_count,
            history_dir.display()
        )));
    }

    Ok(ApplyVersionReport {
        applied_pins: apply_result.applied_pins,
        manifests_found,
        manifests_missing,
        acf_synced_now,
        lua_backup_path: Some(history_dir.display().to_string()),
    })
}
